### PR TITLE
feat: add support for JS project frontend

### PR DESCRIPTION
**Pull request by Unix4ever**
Implement JS as a separate project to enable:
- Jest unit tests.
- EsLint linter.
- build JS project for production and copy `dist` contents to the golang
contaner.
- generate various files for linter, babel, jest.
- update package.json version with the actual version generated by kres.

After looking at file templates decided to implement a new generic
template output.

Potentially can support several frontend projects in the same repo.

Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>

### CODE REVIEW

**Review by smira — COMMENTED** [review]
certainly not an expert in JS, but looks reasonable!

**Review by smira — APPROVED** [review]
lgtm, as long as it works lol :)

**Comment by Unix4ever** [comment]
https://github.com/talos-systems/theila/pull/8 works :)

**Pull request merged**
