### PR TITLE
chore: use Go 1.16 everywhere

### PR DESCRIPTION
**Pull request by AlekSi**
Bump from 1.14.

Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>

### CODE REVIEW

**Review by Unix4ever — APPROVED** [review]

**Review by smira — COMMENTED** [review]
please run Kres on itself to update its own build instructions:

```
make kres
_out/kres gen
```

**Comment by AlekSi** [comment]
```
$  make kres
Makefile:52: *** missing separator.  Stop.
```

That's https://github.com/talos-systems/kres/issues/68. After manually editing Makefile:

```
$ make kres
…
$ _out/kres gen
Failed to execute process '_out/kres'. Reason:
exec: Exec format error
The file '_out/kres' is marked as an executable but could not be run by the operating system.
```

Sure enough, that's a Linux binary.

```
$ go install ./cmd/kres
$ kres gen
internal error: CLI.Name must be specified for autocomplete to work
```

**Comment by AlekSi** [comment]
On Linux, it changes `talos-systems` to `AlekSi` due to
```
$ git remote -v
origin	git@github.com:AlekSi/talos-kres.git (fetch)
origin	git@github.com:AlekSi/talos-kres.git (push)
talos	https://github.com/talos-systems/kres.git (fetch)
talos	https://github.com/talos-systems/kres.git (push)
```

Only after renaming `talks` to `upstream` it worked.

**Comment by smira** [comment]
> On Linux, it changes `talos-systems` to `AlekSi` due to
> 
> ```
> $ git remote -v
> origin	git@github.com:AlekSi/talos-kres.git (fetch)
> origin	git@github.com:AlekSi/talos-kres.git (push)
> talos	https://github.com/talos-systems/kres.git (fetch)
> talos	https://github.com/talos-systems/kres.git (push)
> ```
> 
> Only after renaming `talks` to `upstream` it worked.

PRs are welcome if you have better idea how to detect repository name via git. I'm out of ideas, but at least we support `origin` being upstream and `upstream` being upstream. That's the two standard layouts I'm aware of.

**Review by smira — APPROVED** [review]

**Pull request merged**
